version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ambusmart-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:930309@host.docker.internal:3306/AmbuSmart
    networks:
      - ambu-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ambusmart-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - ambu-network

networks:
  ambu-network:
    driver: bridge
